In [1]:
import torch

In [2]:
x = torch.rand(5, 3)
print(x)
x[1, 1:]

tensor([[0.8452, 0.2777, 0.3381],
        [0.1394, 0.5562, 0.4889],
        [0.1773, 0.5316, 0.0959],
        [0.2567, 0.4664, 0.2446],
        [0.1745, 0.1905, 0.3959]])


tensor([0.5562, 0.4889])

In [3]:
## view() unfolds the tensor in a different shape, using -1 to compute the one dimension.
x.view(-1)

tensor([0.8452, 0.2777, 0.3381, 0.1394, 0.5562, 0.4889, 0.1773, 0.5316, 0.0959,
        0.2567, 0.4664, 0.2446, 0.1745, 0.1905, 0.3959])

In [4]:
torch.cuda.is_available()

True

In [5]:
x = torch.tensor(23)
print('Python Scalar: ', x.item())
x

Python Scalar:  23


tensor(23)